name: flutter_skeleton
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # flutter_localizations:
  #   sdk: flutter
  adivery: ^4.6.1
  archive: ^3.3.6
  audioplayers: ^4.0.1
  crypto: ^3.0.2
  device_info_plus: ^9.0.2
  firebase_analytics: ^10.1.5
  firebase_core: ^2.7.1
  firebase_messaging: ^14.2.6
  flutter_bloc: ^8.1.2
  # flutter_local_notifications: ^14.0.0+2
  flutter_smartlook: ^4.1.2
  flutter_svg: ^2.0.5
  flutter_timezone: ^1.0.6
  gameanalytics_sdk: ^1.2.7
  games_services: ^3.0.1
  google_mobile_ads: ^3.0.0
  http: ^0.13.6
  in_app_purchase: ^3.1.5
  intl: ^0.18.0
  kochava_tracker: ^2.2.0
  path_provider: ^2.0.13
  rive: ^0.9.1
  shared_preferences: ^2.0.18
  unity_ads_plugin: ^0.3.7
  xor_cipher: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  # generate: true

  assets:
    - assets/animations/
    - assets/images/
    - assets/texts/
