name: flutter_skeleton
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.2+100002

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # adivery: ^4.6.1
  archive: ^3.4.8
  audioplayers: ^5.2.0
  crypto: ^3.0.2
  device_info_plus: ^9.1.0
  # firebase_analytics: ^10.6.3
  # firebase_core: ^2.21.0
  # firebase_messaging: ^14.7.3
  # flutter_local_notifications: ^16.1.0
  # flutter_smartlook: ^4.1.9
  flutter_svg: ^2.0.9
  flutter_timezone: ^1.0.8
  get: ^4.6.6
  get_it: ^7.6.7
  # gameanalytics_sdk: ^1.2.7
  # games_services: ^4.0.0
  # google_mobile_ads: ^3.1.0
  # http: ^1.1.0
  in_app_purchase: ^3.1.8
  intl: ^0.18.0
  # kochava_tracker: ^2.4.0
  # metrix_plugin: ^1.5.0
  # onesignal_flutter: ^5.0.3 
  package_info_plus: ^5.0.1
  path_provider: ^2.1.0
  provider: ^6.1.1
  rive: ^0.12.3
  shared_preferences: ^2.2.0
  # unity_ads_plugin: ^0.3.10
  url_launcher: ^6.1.14
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  # generate: true

  assets:
    - assets/animations/
    - assets/images/
    - assets/texts/
    
  fonts:
    - family: LilitaOneSultanAdan
      fonts:
        - asset: assets/fonts/lilitaonesultanadan_bold.ttf
