name: flutter_skeleton
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+100000

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # flutter_localizations:
  #   sdk: flutter
  adivery: ^4.6.1
  archive: ^3.3.6
  audioplayers: ^5.0.1
  collection: ^1.17.2
  crypto: ^3.0.2
  device_info_plus: ^9.0.3
  firebase_analytics: ^10.4.5
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.6
  flutter_bloc: ^8.1.2
  # flutter_local_notifications: ^14.0.0+2
  flutter_smartlook: ^4.1.7
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.7
  flutter_timezone: ^1.0.7
  gameanalytics_sdk: ^1.2.7
  games_services: ^3.0.2
  google_mobile_ads: ^3.0.0
  http: ^1.1.0
  in_app_purchase: ^3.1.8
  intl: ^0.18.0
  kochava_tracker: ^2.2.0
  path_provider: ^2.1.0
  rive: ^0.11.14
  shared_preferences: ^2.2.0
  square_percent_indicater: ^0.1.0
  tcp_socket_connection: ^0.3.1  
  unity_ads_plugin: ^0.3.7
  url_launcher: ^6.1.14
  xor_cipher: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  # generate: true

  assets:
    - assets/animations/
    - assets/images/
    - assets/texts/
    
  fonts:
    - family: LilitaOneSultanAdan
      fonts:
        - asset: assets/fonts/lilitaonesultanadan_bold.ttf
