name: flutter_skeleton
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # flutter_localizations:
  #   sdk: flutter
  archive: ^3.3.6
  audioplayers: ^4.0.1
  crypto: ^3.0.2
  device_info_plus: ^9.0.0
  firebase_analytics: ^10.4.0
  flutter_bloc: ^8.1.2
  flutter_smartlook: ^4.1.2
  flutter_svg: ^2.0.5
  gameanalytics_sdk: ^1.2.7
  google_fonts: ^4.0.4
  google_mobile_ads: ^2.3.0
  http: ^0.13.6
  in_app_purchase: ^3.1.5
  intl: ^0.18.1
  kochava_tracker: ^2.3.0
  logger: ^1.3.0
  path_provider: ^2.0.15
  rive: ^0.11.0
  shared_preferences: ^2.1.1
  unity_ads_plugin: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  # generate: true

  assets:
    - texts/keys.json
    - texts/locale.json

