name: Build and release new version
on:
  push:
    tags:
    - 'i[0-9]+.[0-9]+.[0-9]+*'

jobs:
  release:
    name: build_release
    permissions: write-all
    runs-on: macos-latest
    steps:

      - uses: actions/checkout@v3

      - name: Check Version
        uses: ./.github/actions/check_verion
        
      - uses: ./.github/actions/build
        with:
          ios-certificate-base64: ${{ secrets.IOS_CERTIFICATE_BASE64 }}
          ios-certificate-password: ${{ secrets.IOS_CERTIFICATE_PASS }}
          ios-provisioning-profile-base64: ${{ secrets.IOS_PROVISIONING_PROFILE_BASE64 }}
          ios-keychain-password: ${{ secrets.IOS_GITHUB_KEYCHAIN_PASSWORD }}
          build-apk: false
          build-aab: false

      - name: Get the tag and remove the first character
        id: get_tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          TAG_WITHOUT_FIRST_CHAR=${TAG:1}
          echo "TAG_WITHOUT_FIRST_CHAR=$TAG_WITHOUT_FIRST_CHAR" >> $GITHUB_ENV

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./build/ios/ipa/flutter_build.ipa"
          tag: ${{ env.TAG_WITHOUT_FIRST_CHAR }}