name: Release Tag
on:
  push:
    tags:
    - 'r[0-9]+.[0-9]+.[0-9]+*' 

jobs:
  release:
    name: release
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Build Android and iOS release
        uses: ./.github/actions/build
        with:
          store-base64: ${{ secrets.ANDROID_SIGNING_KEY }}
          store-pass: ${{ secrets.ANDROID_SIGNING_STORE_PASSWORD }}
          key-alias: ${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}
          key-pass: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./build/app/outputs/apk/release/*.apk,./build/app/outputs/bundle/release/app-release.aab"
          tag: $GITHUB_REF_NAME